/** Shared, compact instructions used by prompt exports and agent setup. */
export const EXECUTION_CONTRACT = `**HELEN execution contract**
- **Acceptance**: preserve intent; define observable task behavior and checks before edits, not just "describe an approach". AUDIT/RESEARCH stay read-only unless remediation is authorized.
- **Model cascade**: choose the cheapest available model capable of the task when routing is supported; verify acceptance and escalate on evidenced failure or capability limits. If the primary model cannot be changed, keep it when finishing costs less than a handoff. Record measured usage when available; never invent savings.
- **Parallelism**: use one agent for small cohesive tasks. Delegate only when expertise, smaller context or independent work is expected to improve acceptance or lower total cost after context transfer, coordination, integration, verification and retries. When worthwhile, give specialists exclusive ownership and compact briefs; run independent work concurrently. Flash is an option only if available and suitable, never a mandatory tier. Integrate and verify their work.
- **Latency**: minimize time to a verified result without weakening acceptance. Answer directly when supplied facts suffice; otherwise retrieve only missing evidence. Batch independent reads and checks; keep dependent edits and checks ordered. Avoid repeated planning, polling and unchanged work; report outcomes concisely. Speed never justifies guessing, skipping required checks or lowering reasoning effort automatically.
- **Verification**: use focused regression checks during fixes and reuse unchanged passing evidence; run the full repository CI gate before completion. Prefer an available direct browser MCP for DOM and interaction evidence; UI changes require Chromium verification via Playwright or that browser MCP at 375, 768, 1440 px. Report unavailable checks honestly.
- **Improvement discovery**: after checks, ask what further useful improvements remain; inspect evidence, apply authorized fixes, verify, and repeat without an arbitrary retry cap. Finish when acceptance passes and a fresh scan finds no actionable improvements; report external blockers and residual risks. Never claim perfection.
- **Token economy**: concise English instructions, relevant context only, no repeated rules or unchanged checks; answer in the user's language. Keep shared instructions as a stable prefix and variable task facts after it. Use provider prompt caching when supported; verify cache-hit usage rather than claiming caching or savings from text layout alone.`;
