import fs from 'node:fs';
import path from 'node:path';
import { PHASE_PATTERN, getPromptsRoot, listPromptEntries, shortId, type PromptEntry } from './prompts.js';

export const INDEX_START = '<!-- HELEN:INDEX:START (generated by `helen prompts index`, do not edit) -->';
export const INDEX_END = '<!-- HELEN:INDEX:END -->';

function typeLabel(entry: PromptEntry): string {
  if (entry.kind === 'flow') return `${entry.action ?? 'APPLY'} flow`;
  if (entry.kind === 'checkpoint') return 'checkpoint';
  return entry.action ?? 'prompt';
}

export function renderPhaseIndex(phase: string, root: string = getPromptsRoot()): string {
  const rows = listPromptEntries(root)
    .filter(entry => entry.phase === phase)
    .map(entry => {
      const link = path.posix.relative(phase, entry.relativePath);
      return `| [${shortId(entry)}](${link}) | ${typeLabel(entry)} | ${entry.summary} |`;
    });
  return [INDEX_START, '| Prompt | Type | Summary |', '|---|---|---|', ...rows, INDEX_END].join('\n');
}

function withIndex(content: string, index: string): string {
  const start = content.indexOf(INDEX_START);
  const end = content.indexOf(INDEX_END);
  if (start === -1 || end < start) return `${content.replace(/\s*$/, '')}\n\n## Prompts\n\n${index}\n`;
  return `${content.slice(0, start)}${index}${content.slice(end + INDEX_END.length)}`;
}

/**
 * Regenerate the prompt table of every phase README from prompt frontmatter.
 * Returns the READMEs that were (or, with write=false, would be) changed.
 */
export function updatePhaseIndexes(write: boolean, root: string = getPromptsRoot()): string[] {
  const changed: string[] = [];
  const phases = fs.readdirSync(root, { withFileTypes: true }).filter(entry => entry.isDirectory() && PHASE_PATTERN.test(entry.name));
  for (const phase of phases) {
    const readme = path.join(root, phase.name, 'README.md');
    const currentRaw = fs.existsSync(readme) ? fs.readFileSync(readme, 'utf-8') : `# ${phase.name}\n`;
    const isCrlf = currentRaw.includes('\r\n');
    const current = currentRaw.replace(/\r\n/g, '\n');
    const nextNormalized = withIndex(current, renderPhaseIndex(phase.name, root));
    if (nextNormalized !== current) {
      changed.push(path.relative(root, readme).replace(/\\/g, '/'));
      if (write) {
        const next = isCrlf ? nextNormalized.replace(/\n/g, '\r\n') : nextNormalized;
        fs.writeFileSync(readme, next, 'utf-8');
      }
    }
  }
  return changed;
}
